#!/bin/bash

echo "🔐 DHA Digital Services - Environment Setup Guide"
echo "=================================================="
echo ""
echo "⚠️  IMPORTANT: Use Replit Secrets Tool to set these variables"
echo ""
echo "📋 Required Secrets to Add:"
echo ""
echo "1. Open the Secrets tool (🔒 icon in left sidebar)"
echo "2. Add each of these secrets:"
echo ""
echo "=== Certificate & Auth Keys ==="
echo "CERT_KEY_IDENTIFIER"
echo "CERT_API_KEY"
echo "SIG_API"
echo "AUTH_API_KEY"
echo ""
echo "=== API URLs ==="
echo "OCI"
echo "AUTH_URI"
echo "SAPS_URI"
echo "SAPS_CRC_BASE_URL"
echo "DHA_NPR_BASE_URL"
echo "ICAO_PKD_BASE_URL"
echo "DHA_ABIS_BASE_URL"
echo "SITA_ESERVICES_BASE_URL"
echo ""
echo "=== Government API Keys ==="
echo "DHA_ABIS_API_KEY"
echo "SAPS_CRC_API_KEY"
echo "SITA_ESERVICES_API_KEY"
echo ""
echo "=== Security Keys ==="
echo "ADMIN_API_KEY"
echo "SESSION_SECRET"
echo "ENCRYPTION_KEY"
echo "JWT_SECRET"
echo "MASTER_ENCRYPTION_KEY"
echo "QUANTUM_MASTER_KEY"
echo ""
echo "=== Database ==="
echo "DATABASE_URL"
echo "PGHOST"
echo ""
echo "=== Optional ==="
echo "GITHUB_TOKEN"
echo "OPENAI_API_KEY"
echo "ANTHROPIC_API_KEY"
echo ""
echo "✅ After adding secrets, restart your Repl for changes to take effect"